// @flow

// leave off @2x/@3x
const images = {
  bg: require('../Images/BG.png'),
  explodingStar: require('../Images/exploding-star.png'),
  heart: require('../Images/heart.png'),
  igniteLogo: require('../Images/ignite_logo.png'),
  ir: require('../Images/ir.png'),
  rep: require('../Images/rep.png'),
  segmented: require('../Images/segmented.png'),
  setAlerts: require('../Images/set-alerts.png'),
  social: require('../Images/social.png'),
  thumbsupDown: require('../Images/thumbsup-down.png'),
  tileBg: require('../Images/tile_bg.png'),
  topLogo: require('../Images/top_logo.png'),
  x: require('../Images/x.png'),
  bg: require('../Images/BG.png'),
  explodingStar: require('../Images/exploding-star.png'),
  heart: require('../Images/heart.png'),
  igniteLogo: require('../Images/ignite_logo.png'),
  ir: require('../Images/ir.png'),
  segmented: require('../Images/segmented.png'),
  social: require('../Images/social.png'),
  tileBg: require('../Images/tile_bg.png'),
  topLogo: require('../Images/top_logo.png'),
  x: require('../Images/x.png'),
  bg: require('../Images/BG.png'),
  explodingStar: require('../Images/exploding-star.png'),
  heart: require('../Images/heart.png'),
  igniteLogo: require('../Images/ignite_logo.png'),
  ir: require('../Images/ir.png'),
  segmented: require('../Images/segmented.png'),
  tileBg: require('../Images/tile_bg.png'),
  topLogo: require('../Images/top_logo.png'),
  x: require('../Images/x.png'),
  bg: require('../Images/BG.png'),
  explodingStar: require('../Images/exploding-star.png'),
  heart: require('../Images/heart.png'),
  igniteLogo: require('../Images/ignite_logo.png'),
  ir: require('../Images/ir.png'),
  tileBg: require('../Images/tile_bg.png'),
  topLogo: require('../Images/top_logo.png'),
  x: require('../Images/x.png'),
  bg: require('../Images/BG.png'),
  heart: require('../Images/heart.png'),
  igniteLogo: require('../Images/ignite_logo.png'),
  ir: require('../Images/ir.png'),
  tileBg: require('../Images/tile_bg.png'),
  topLogo: require('../Images/top_logo.png'),
  x: require('../Images/x.png'),
  logo: require('../Images/ir.png'),
  clearLogo: require('../Images/top_logo.png'),
  ignite: require('../Images/ignite_logo.png'),
  tileBg: require('../Images/tile_bg.png'),
  background: require('../Images/BG.png')
}

export default images
